language: dart
dart:
  - stable
  - dev
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
services: mongodb
before_script:
  - sleep 15
sudo: false
cache:
  directories:
  - $HOME/.pub-cache
script: pub run test
