#library("all_tests");
#import("../lib/bson/bson.dart");
#import("bson/bson_tests_vm.dart",prefix:"bson");
#import("objectory/all_objectory_tests.dart",prefix:"objectory");
#import("database_tests.dart",prefix:"database");
main(){
  bson.main();
  database.main();          
  objectory.main();
}